#!/bin/bash
# Test script for video playback fixes

echo "🎥 Video Playback Test Guide"
echo "================================"
echo ""
echo "1. Check if chatbot is running:"
ps aux | grep -E "chatbot-ui|dist/index" | grep -v grep
echo ""
echo "2. To view live logs during testing:"
echo "   tail -f chatbot_output.log | grep -E 'ChatFlow|Video Player|Frame'"
echo ""
echo "3. Test scenarios:"
echo ""
echo "   a) Test recording + immediate playback:"
echo "      Say: 'Shoot a 5 second video and play it back'"
echo "      Expected: Record video → TTS → Play all frames smoothly"
echo ""
echo "   b) Test playback only:"
echo "      Say: 'Play the last video'"
echo "      Expected: Play all frames smoothly, not just one frame"
echo ""
echo "   c) Test recording preview:"
echo "      Say: 'Record a 10 second video'"
echo "      Expected: See live camera preview during recording"
echo ""
echo "4. What to look for in logs:"
echo "   ✓ 'Starting visual mode: playback'"
echo "   ✓ 'PLAYBACK MODE - Starting video playback process'"
echo "   ✓ 'Extracted XXX frames'"
echo "   ✓ 'Frame #10 updated (size: XXXX bytes)'"
echo "   ✓ 'Video playback exited with code 0'"
echo "   ✓ 'Playback duration: X.XXs'"
echo ""
echo "5. Manual video player test:"
echo "   cd /home/dash/whisplay-ai-chatbot"
echo "   python3 python/video_player_lcd.py play data/videos/video-*.h264"
echo ""
echo "6. Check video file:"
echo "   ls -lh data/videos/ | tail -3"
echo ""
echo "Ready to test! 🚀"


